import { snapshotSchema } from '@incidentos/contracts';
import { readConfig } from '../src/config.js';
import { Store } from '../src/store.js';
import { Incidents } from '../src/domain.js';
import { Agents } from '../src/agents.js';
import { FixtureChannel, Notifications } from '../src/notifications.js';
const store = await Store.open(':memory:');
const config = readConfig({ DASHBOARD_TOKEN: 'fixture-generator-not-a-real-secret', INCIDENTOS_MODE: 'fixture' });
const domain = new Incidents(store, config);
const agents = new Agents(domain, new Notifications(domain, new FixtureChannel()));
const i = domain.create({ team: 'TDEMO', channel: 'CDEMO', ts: '1.000001', user: 'UREPORTER', text: 'Forklift incident at Loading Dock B' });
const id = i.snapshot.incidentId; const snapshots: Record<string, unknown> = { idle: i.snapshot };
await agents.process(id); snapshots.coordinating = domain.get(id).snapshot;
domain.agent(id, 'communications', 'waiting', 'Waiting for ULEAD acknowledgement'); snapshots.waiting = domain.get(id).snapshot;
domain.mutate(id, 'Fixture: conflicting witness observation', current => { current.snapshot.tasks[1].status = 'needs_review'; current.snapshot.tasks[1].blockedReason = 'Witness report conflicts with earlier area-status report'; });
domain.agent(id, 'evidence', 'blocked', 'Lead must reconcile the two observations'); snapshots.contradiction = domain.get(id).snapshot;
domain.agent(id, 'communications', 'failed', 'Fixture delivery error'); snapshots.failed = domain.get(id).snapshot;
domain.report(id, 'Synthetic handoff with open tasks assigned to named owners.', ['1.000001']);
domain.handoff(id, 'USUPERVISOR', domain.get(id).snapshot.version); snapshots.handed_over = domain.get(id).snapshot;
for (const snapshot of Object.values(snapshots)) snapshotSchema.parse(snapshot);
console.log(JSON.stringify(snapshots, null, 2)); store.close();
